ci: don't create nightly build on pushing stable ver tag

diff --git a/.github/workflows/nightly-release.yml b/.github/workflows/nightly-release.yml
--- a/.github/workflows/nightly-release.yml
+++ b/.github/workflows/nightly-release.yml
@@ -4,9 +4,6 @@ on:
   push:
     branches:
       - main
-    tags:
-      # create nightly releases for tag pushes so you can easily track the first nightly release on a certain stable release
-      - 'v[0-9]+.[0-9]+.[0-9]+'
   workflow_dispatch:
     inputs:
       semver_name:
@@ -48,10 +45,6 @@ jobs:
 
           if [ "$CUSTOM_VERSION_NAME" != "" ]; then
             echo "next_version_name_for_tags=${CUSTOM_VERSION_NAME}-nightly.${PRERELEASE_BUILD_NO}" >> "$GITHUB_OUTPUT"
-          elif [[ "$GITHUB_REF" = refs/tags/* ]]; then
-            # we've already checked that the ref is a tag with the v prefix
-            next_version_name_for_tags=$(echo "${GITHUB_REF_NAME}-nightly.0" | cut -c2-)
-            echo "next_version_name_for_tags=${next_version_name_for_tags}" >> "$GITHUB_OUTPUT"
           elif latest_tag_name=$(git describe --tags `git rev-list --tags --max-count=1`); then
             next_version_name_for_tags=$(npx semver "$latest_tag_name" -i prerelease)
             echo "next_version_name_for_tags=${next_version_name_for_tags}" >> "$GITHUB_OUTPUT"
@@ -64,7 +57,7 @@ jobs:
           next_version_name_for_assemblies=$(echo ${next_version_name_for_tags} | sed -E 's/v?([0-9]{1,5})\.([0-9]{1,5})\.([0-9]{1,5})-nightly\.([0-9]{1,5})/\1.\2.\3.\4/')
 
           if [ "$next_version_name_for_assemblies" == "$next_version_name_for_tags" ]; then
-            >&2 echo "Failed to create the version string for the ASI and the scripting DLLs because the version tag is ill-formed as a nightly version tag. Tag name: $next_version_name_for_tags"
+            >&2 echo "Failed to create the version string for the ASI and the scripting DLLs because the version tag is ill-formed as a nightly version tag. Tag name: ${next_version_name_for_tags}"
             exit 1
           fi
 
